config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  belongs_to :cocktail
  belongs_to :ingredient
  validates_uniqueness_of :ingredient, scope: :cocktail_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
  has_many :cocktails, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]
  def index
    @cocktails = Cocktail.all
  end

  def show
    @doses = @cocktail.doses
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # GET /cocktails/1/edit
  def edit
    @dose = Dose.new
  end

  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: 'cocktail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
  # Only allow a list of trusted parameters through.
  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail
  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @dose.save
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
   </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<%= render 'form', cockctail: @cockctail %>

<%= link_to 'Show', @cockctail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
    <div class="d-flex justify-content ajuste">
      <h1>All cocktails</h1>
      <%= link_to 'Adicionar', new_cocktail_path, class: 'btn btn-primary' %>
    </div>
  <div class="row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-4">
          <div class="flexpower">
            <%= link_to cocktail_path(cocktail) do %>
              <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="https://source.unsplash.com/random?sig=<%= cocktail.id %>" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title"><%= cocktail.name %></h5>
                    <p class="card-text"><%= cocktail.doses.first.try(:description) %> <%= cocktail.doses.first.try(:ingredient).try(:name)%></p>
                    <a href="cocktails/<%= cocktail.id %>" class="btn btn-primary">Edit</a>
                    <%= link_to cocktail_path(cocktail.id), method: :delete, data: {:confirm => "You sure?" } do  %>
                      <i class="fas fa-trash"></i>
                    <% end %>
                  </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
  </div>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cocktail.name %>
</p>

<p>
  <strong>Doses:</strong>
  <% @doses.each do |dose| %>
    <%= dose.description %> <%= dose.ingredient.name %>
  <% end%>
</p>



<%= link_to 'Edit', edit_cocktail_path(@cocktail) %> |
<%= link_to 'Adicione as doses', new_cocktail_dose_path(@cocktail) %> |
<%= link_to 'Back', cocktails_path %>

app/views/doses/new.html.erb
<%= simple_form_for [ @cocktail, @dose ] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "Edite o coquetel", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application','data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= yield %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>